In [1]:
import pandas as pd
import matplotlib.pyplot as mp
import sqlite3
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

In [2]:
df = pd.read_csv("netflix_titles.csv",encoding = 'latin1')

In [3]:
df.shape

(8807, 12)

In [29]:
df.tail(30)

     show_id     type               title                 director                                               cast               country date_added  release_year rating   duration                 listed_in                                        description  added_year  added_month added_month_name  content_age  duration_minutes  seasons
8797   s8798  TV Show           Zak Storm                  unknown  Michael Johnston, Jessica Gee-George, Christin...                France 2018-09-13          2016  TV-Y7  3 Seasons                  Kids' TV  Teen surfer Zak Storm is mysteriously transpor...      2018.0          9.0        September          2.0               NaN      3.0
8797   s8798  TV Show           Zak Storm                  unknown  Michael Johnston, Jessica Gee-George, Christin...           South Korea 2018-09-13          2016  TV-Y7  3 Seasons                  Kids' TV  Teen surfer Zak Storm is mysteriously transpor...      2018.0          9.0        September          2.0               NaN      3.0
8797   s8798  TV Show           Zak Storm                  unknown  Michael Johnston, Jessica Gee-George, Christin...             Indonesia 2018-09-13          2016  TV-Y7  3 Seasons                  Kids' TV  Teen surfer Zak Storm is mysteriously transpor...      2018.0          9.0        September          2.0               NaN      3.0
8798   s8799    Movie            Zed Plus  Chandra Prakash Dwivedi  Adil Hussain, Mona Singh, K.K. Raina, Sanjay M...                 India 2019-12-31          2014  TV-MA    131 min                  Comedies  A philandering small-town mechanic's political...      2019.0         12.0         December          5.0             131.0      NaN
8798   s8799    Movie            Zed Plus  Chandra Prakash Dwivedi  Adil Hussain, Mona Singh, K.K. Raina, Sanjay M...                 India 2019-12-31          2014  TV-MA    131 min                    Dramas  A philandering small-town mechanic's political...      2019.0         12.0         December          5.0             131.0      NaN
8798   s8799    Movie            Zed Plus  Chandra Prakash Dwivedi  Adil Hussain, Mona Singh, K.K. Raina, Sanjay M...                 India 2019-12-31          2014  TV-MA    131 min      International Movies  A philandering small-town mechanic's political...      2019.0         12.0         December          5.0             131.0      NaN
8799   s8800    Movie               Zenda           Avadhoot Gupte  Santosh Juvekar, Siddharth Chandekar, Sachit P...                 India 2018-02-15          2009  TV-14    120 min                    Dramas  A change in the leadership of a political part...      2018.0          2.0         February          9.0             120.0      NaN
8799   s8800    Movie               Zenda           Avadhoot Gupte  Santosh Juvekar, Siddharth Chandekar, Sachit P...                 India 2018-02-15          2009  TV-14    120 min      International Movies  A change in the leadership of a political part...      2018.0          2.0         February          9.0             120.0      NaN
8800   s8801  TV Show  Zindagi Gulzar Hai                  unknown  Sanam Saeed, Fawad Khan, Ayesha Omer, Mehreen ...              Pakistan 2016-12-15          2012  TV-PG   1 Season    International TV Shows  Strong-willed, middle-class Kashaf and carefre...      2016.0         12.0         December          4.0               NaN      1.0
8800   s8801  TV Show  Zindagi Gulzar Hai                  unknown  Sanam Saeed, Fawad Khan, Ayesha Omer, Mehreen ...              Pakistan 2016-12-15          2012  TV-PG   1 Season         Romantic TV Shows  Strong-willed, middle-class Kashaf and carefre...      2016.0         12.0         December          4.0               NaN      1.0
8800   s8801  TV Show  Zindagi Gulzar Hai                  unknown  Sanam Saeed, Fawad Khan, Ayesha Omer, Mehreen ...              Pakistan 2016-12-15          2012  TV-PG   1 Season                 TV Dramas  Strong-willed, middle-class Kashaf and carefre...      2016.0         12.0         December          4.0               NaN      1.0
8801   s8802    Movie             Zinzana          Majid Al Ansari  Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...  United Arab Emirates 2016-03-09          2015  TV-MA     96 min                    Dramas  Recovering alcoholic Talal wakes up inside a s...      2016.0          3.0            March          1.0              96.0      NaN
8801   s8802    Movie             Zinzana          Majid Al Ansari  Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...  United Arab Emirates 2016-03-09          2015  TV-MA     96 min      International Movies  Recovering alcoholic Talal wakes up inside a s...      2016.0          3.0            March          1.0              96.0      NaN
8801   s8802    Movie             Zinzana          Majid Al Ansari  Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...  United Arab Emirates 2016-03-09          2015  TV-MA     96 min                 Thrillers  Recovering alcoholic Talal wakes up inside a s...      2016.0          3.0            March          1.0              96.0      NaN
8801   s8802    Movie             Zinzana          Majid Al Ansari  Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...                Jordan 2016-03-09          2015  TV-MA     96 min                    Dramas  Recovering alcoholic Talal wakes up inside a s...      2016.0          3.0            March          1.0              96.0      NaN
8801   s8802    Movie             Zinzana          Majid Al Ansari  Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...                Jordan 2016-03-09          2015  TV-MA     96 min      International Movies  Recovering alcoholic Talal wakes up inside a s...      2016.0          3.0            March          1.0              96.0      NaN
8801   s8802    Movie             Zinzana          Majid Al Ansari  Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...                Jordan 2016-03-09          2015  TV-MA     96 min                 Thrillers  Recovering alcoholic Talal wakes up inside a s...      2016.0          3.0            March          1.0              96.0      NaN
8802   s8803    Movie              Zodiac            David Fincher  Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...         United States 2019-11-20          2007      R    158 min               Cult Movies  A political cartoonist, a crime reporter and a...      2019.0         11.0         November         12.0             158.0      NaN
8802   s8803    Movie              Zodiac            David Fincher  Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...         United States 2019-11-20          2007      R    158 min                    Dramas  A political cartoonist, a crime reporter and a...      2019.0         11.0         November         12.0             158.0      NaN
8802   s8803    Movie              Zodiac            David Fincher  Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...         United States 2019-11-20          2007      R    158 min                 Thrillers  A political cartoonist, a crime reporter and a...      2019.0         11.0         November         12.0             158.0      NaN
8803   s8804  TV Show         Zombie Dumb                  unknown                                            unknown               unknown 2019-07-01          2018  TV-Y7  2 Seasons                  Kids' TV  While living alone in a spooky town, a young g...      2019.0          7.0             July          1.0               NaN      2.0
8803   s8804  TV Show         Zombie Dumb                  unknown                                            unknown               unknown 2019-07-01          2018  TV-Y7  2 Seasons           Korean TV Shows  While living alone in a spooky town, a young g...      2019.0          7.0             July          1.0               NaN      2.0
8803   s8804  TV Show         Zombie Dumb                  unknown                                            unknown               unknown 2019-07-01          2018  TV-Y7  2 Seasons               TV Comedies  While living alone in a spooky town, a young g...      2019.0          7.0             July          1.0               NaN      2.0
8804   s8805    Movie          Zombieland          Ruben Fleischer  Jesse Eisenberg, Woody Harrelson, Emma Stone, ...         United States 2019-11-01          2009      R     88 min                  Comedies  Looking to survive in a world taken over by zo...      2019.0         11.0         November         10.0              88.0      NaN
8804   s8805    Movie          Zombieland          Ruben Fleischer  Jesse Eisenberg, Woody Harrelson, Emma Stone, ...         United States 2019-11-01          2009      R     88 min             Horror Movies  Looking to survive in a world taken over by zo...      2019.0         11.0         November         10.0              88.0      NaN
8805   s8806    Movie                Zoom             Peter Hewitt  Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...         United States 2020-01-11          2006     PG     88 min  Children & Family Movies  Dragged from civilian life, a former superhero...      2020.0          1.0          January         14.0              88.0      NaN
8805   s8806    Movie                Zoom             Peter Hewitt  Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...         United States 2020-01-11          2006     PG     88 min                  Comedies  Dragged from civilian life, a former superhero...      2020.0          1.0          January         14.0              88.0      NaN
8806   s8807    Movie              Zubaan              Mozez Singh  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...                 India 2019-03-02          2015  TV-14    111 min                    Dramas  A scrappy but poor boy worms his way into a ty...      2019.0          3.0            March          4.0             111.0      NaN
8806   s8807    Movie              Zubaan              Mozez Singh  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...                 India 2019-03-02          2015  TV-14    111 min      International Movies  A scrappy but poor boy worms his way into a ty...      2019.0          3.0            March          4.0             111.0      NaN
8806   s8807    Movie              Zubaan              Mozez Singh  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...                 India 2019-03-02          2015  TV-14    111 min          Music & Musicals  A scrappy but poor boy worms his way into a ty...      2019.0          3.0            March          4.0             111.0      NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [6]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added', 'release_year', 'rating', 'duration', 'listed_in', 'description'], dtype='object')

In [7]:
df['director'] = df['director'].fillna('unknown')

In [8]:
df['cast'] = df['cast'].fillna('unknown')
df['country'] = df['country'].fillna('unknown')
df['rating'] = df['rating'].fillna('unknown')
df['duration'] = df['duration'].fillna('unknown')

In [9]:
df['date_added'] = pd.to_datetime(df['date_added'],errors = 'coerce')

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_8528\44827034.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['date_added'] = pd.to_datetime(df['date_added'],errors = 'coerce')

In [10]:
df['country'] = df['country'].str.split(',')

In [11]:
#Remove extra spaces
df['country'] = df['country'].apply(lambda x: [c.strip() for c in x])
#Explode into multiple rows
df = df.explode('country')

In [12]:
df['listed_in'] = df['listed_in'].str.split(',')
df['listed_in'] = df['listed_in'].apply(lambda x: [c.strip() for c in x])
df = df.explode('listed_in')

In [13]:
df['added_year']  = df['date_added'].dt.year

In [14]:
df['added_month']  = df['date_added'].dt.month

In [15]:
df['added_month_name'] = df['date_added'].dt.month_name()

In [16]:
df['content_age'] = df['added_year'] - df['release_year']

In [17]:
# extract numeric part
df['duration_value'] = df['duration'].str.extract(r'(\d+)').astype(float)

# create movie duration column
df['duration_minutes'] = df.apply(
    lambda x: x['duration_value'] if x['type'] == 'Movie' else None,
    axis=1
)

# create tv show seasons column
df['seasons'] = df.apply(
    lambda x: x['duration_value'] if x['type'] == 'TV Show' else None,
    axis=1
)

In [18]:
df = df.drop('duration_value', axis=1)

In [19]:
conn = sqlite3.connect('dfanalysis.db')

In [20]:
df.to_sql('netflix_cleaned',conn,if_exists='replace',index=False)

23764

In [21]:
conn.execute("DROP TABLE IF EXISTS df;")
conn.commit()

In [22]:
type_ = conn.execute("""SELECT 
    type,
    COUNT(*) AS total_count
FROM netflix_cleaned
GROUP BY type;""")

In [68]:
df.to_csv("netflix_cleaned.csv", index=False)

In [24]:
all = conn.execute('select * from netflix_cleaned')

In [25]:
all.fetchall()

[('s1',
  'Movie',
  'Dick Johnson Is Dead',
  'Kirsten Johnson',
  'unknown',
  'United States',
  '2021-09-25 00:00:00',
  2020,
  'PG-13',
  '90 min',
  'Documentaries',
  'As her father nears the end of his life, filmmaker Kirsten Johnson stages his death in inventive and comical ways to help them both face the inevitable.',
  2021.0,
  9.0,
  'September',
  1.0,
  90.0,
  None),
 ('s2',
  'TV Show',
  'Blood & Water',
  'unknown',
  'Ama Qamata, Khosi Ngema, Gail Mabalane, Thabang Molaba, Dillon Windvogel, Natasha Thahane, Arno Greeff, Xolile Tshabalala, Getmore Sithole, Cindy Mahlangu, Ryle De Morny, Greteli Fincham, Sello Maake Ka-Ncube, Odwa Gwanya, Mekaila Mathys, Sandi Schultz, Duane Williams, Shamilla Miller, Patrick Mofokeng',
  'South Africa',
  '2021-09-24 00:00:00',
  2021,
  'TV-MA',
  '2 Seasons',
  'International TV Shows',
  'After crossing paths at a party, a Cape Town teen sets out to prove whether a private-school swimming star is her sister who was abducted at birth.',
  2021.0,
  9.0,
  'September',
  0.0,
  None,
  2.0),
 ('s2',
  'TV Show',
  'Blood & Water',
  'unknown',
  'Ama Qamata, Khosi Ngema, Gail Mabalane, Thabang Molaba, Dillon Windvogel, Natasha Thahane, Arno Greeff, Xolile Tshabalala, Getmore Sithole, Cindy Mahlangu, Ryle De Morny, Greteli Fincham, Sello Maake Ka-Ncube, Odwa Gwanya, Mekaila Mathys, Sandi Schultz, Duane Williams, Shamilla Miller, Patrick Mofokeng',
  'South Africa',
  '2021-09-24 00:00:00',
  2021,
  'TV-MA',
  '2 Seasons',
  'TV Dramas',
  'After crossing paths at a party, a Cape Town teen sets out to prove whether a private-school swimming star is her sister who was abducted at birth.',
  2021.0,
  9.0,
  'September',
  0.0,
  None,
  2.0),
 ('s2',
  'TV Show',
  'Blood & Water',
  'unknown',
  'Ama Qamata, Khosi Ngema, Gail Mabalane, Thabang Molaba, Dillon Windvogel, Natasha Thahane, Arno Greeff, Xolile Tshabalala, Getmore Sithole, Cindy Mahlangu, Ryle De Morny, Greteli Fincham, Sello Maake Ka-Ncube, Odwa Gwanya, Mekaila Mathys, Sandi Schultz, Duane Williams, Shamilla Miller, Patrick Mofokeng',
  'South Africa',
  '2021-09-24 00:00:00',
  2021,
  'TV-MA',
  '2 Seasons',
  'TV Mysteries',
  'After crossing paths at a party, a Cape Town teen sets out to prove whether a private-school swimming star is her sister who was abducted at birth.',
  2021.0,
  9.0,
  'September',
  0.0,
  None,
  2.0),
 ('s3',
  'TV Show',
  'Ganglands',
  'Julien Leclercq',
  'Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabiha Akkari, Sofia Lesaffre, Salim Kechiouche, Noureddine Farihi, Geert Van Rampelberg, Bakary Diombera',
  'unknown',
  '2021-09-24 00:00:00',
  2021,
  'TV-MA',
  '1 Season',
  'Crime TV Shows',
  'To protect his family from a powerful drug lord, skilled thief Mehdi and his expert team of robbers are pulled into a violent and deadly turf war.',
  2021.0,
  9.0,
  'September',
  0.0,
  None,
  1.0),
 ('s3',
  'TV Show',
  'Ganglands',
  'Julien Leclercq',
  'Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabiha Akkari, Sofia Lesaffre, Salim Kechiouche, Noureddine Farihi, Geert Van Rampelberg, Bakary Diombera',
  'unknown',
  '2021-09-24 00:00:00',
  2021,
  'TV-MA',
  '1 Season',
  'International TV Shows',
  'To protect his family from a powerful drug lord, skilled thief Mehdi and his expert team of robbers are pulled into a violent and deadly turf war.',
  2021.0,
  9.0,
  'September',
  0.0,
  None,
  1.0),
 ('s3',
  'TV Show',
  'Ganglands',
  'Julien Leclercq',
  'Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabiha Akkari, Sofia Lesaffre, Salim Kechiouche, Noureddine Farihi, Geert Van Rampelberg, Bakary Diombera',
  'unknown',
  '2021-09-24 00:00:00',
  2021,
  'TV-MA',
  '1 Season',
  'TV Action & Adventure',
  'To protect his family from a powerful drug lord, skilled thief Mehdi and his expert team of robbers are pulled into a violent and deadly turf war.',
  2021.0,
  9.0,
  'September',
  0.0,
  None,
  1.0),
 ('s4',
  'TV Show',
  'Jailbirds New Orleans',
  'unknown',
  'unknown',
  'unknown',
  '2021-09-24 00:00:00',
  2021,
  'TV-MA',
  '1 Season',
  'Docuseries',
  'Feuds, flirtations and toilet talk go down among the incarcerated women at the Orleans Justice Center in New Orleans on this gritty reality series.',
  2021.0,
  9.0,
  'September',
  0.0,
  None,
  1.0),
 ('s4',
  'TV Show',
  'Jailbirds New Orleans',
  'unknown',
  'unknown',
  'unknown',
  '2021-09-24 00:00:00',
  2021,
  'TV-MA',
  '1 Season',
  'Reality TV',
  'Feuds, flirtations and toilet talk go down among the incarcerated women at the Orleans Justice Center in New Orleans on this gritty reality series.',
  2021.0,
  9.0,
  'September',
  0.0,
  None,
  1.0),
 ('s5',
  'TV Show',
  'Kota Factory',
  'unknown',
  'Mayur More, Jitendra Kumar, Ranjan Raj, Alam Khan, Ahsaas Channa, Revathi Pillai, Urvi Singh, Arun Kumar',
  'India',
  '2021-09-24 00:00:00',
  2021,
  'TV-MA',
  '2 Seasons',
  'International TV Shows',
  'In a city of coaching centers known to train Indiaâ\x80\x99s finest collegiate minds, an earnest but unexceptional student and his friends navigate campus life.',
  2021.0,
  9.0,
  'September',
  0.0,
  None,
  2.0),
 ('s5',
  'TV Show',
  'Kota Factory',
  'unknown',
  'Mayur More, Jitendra Kumar, Ranjan Raj, Alam Khan, Ahsaas Channa, Revathi Pillai, Urvi Singh, Arun Kumar',
  'India',
  '2021-09-24 00:00:00',
  2021,
  'TV-MA',
  '2 Seasons',
  'Romantic TV Shows',
  'In a city of coaching centers known to train Indiaâ\x80\x99s finest collegiate minds, an earnest but unexceptional student and his friends navigate campus life.',
  2021.0,
  9.0,
  'September',
  0.0,
  None,
  2.0),
 ('s5',
  'TV Show',
  'Kota Factory',
  'unknown',
  'Mayur More, Jitendra Kumar, Ranjan Raj, Alam Khan, Ahsaas Channa, Revathi Pillai, Urvi Singh, Arun Kumar',
  'India',
  '2021-09-24 00:00:00',
  2021,
  'TV-MA',
  '2 Seasons',
  'TV Comedies',
  'In a city of coaching centers known to train Indiaâ\x80\x99s finest collegiate minds, an earnest but unexceptional student and his friends navigate campus life.',
  2021.0,
  9.0,
  'September',
  0.0,
  None,
  2.0),
 ('s6',
  'TV Show',
  'Midnight Mass',
  'Mike Flanagan',
  'Kate Siegel, Zach Gilford, Hamish Linklater, Henry Thomas, Kristin Lehman, Samantha Sloyan, Igby Rigney, Rahul Kohli, Annarah Cymone, Annabeth Gish, Alex Essoe, Rahul Abburi, Matt Biedel, Michael Trucco, Crystal Balint, Louis Oliver',
  'unknown',
  '2021-09-24 00:00:00',
  2021,
  'TV-MA',
  '1 Season',
  'TV Dramas',
  'The arrival of a charismatic young priest brings glorious miracles, ominous mysteries and renewed religious fervor to a dying town desperate to believe.',
  2021.0,
  9.0,
  'September',
  0.0,
  None,
  1.0),
 ('s6',
  'TV Show',
  'Midnight Mass',
  'Mike Flanagan',
  'Kate Siegel, Zach Gilford, Hamish Linklater, Henry Thomas, Kristin Lehman, Samantha Sloyan, Igby Rigney, Rahul Kohli, Annarah Cymone, Annabeth Gish, Alex Essoe, Rahul Abburi, Matt Biedel, Michael Trucco, Crystal Balint, Louis Oliver',
  'unknown',
  '2021-09-24 00:00:00',
  2021,
  'TV-MA',
  '1 Season',
  'TV Horror',
  'The arrival of a charismatic young priest brings glorious miracles, ominous mysteries and renewed religious fervor to a dying town desperate to believe.',
  2021.0,
  9.0,
  'September',
  0.0,
  None,
  1.0),
 ('s6',
  'TV Show',
  'Midnight Mass',
  'Mike Flanagan',
  'Kate Siegel, Zach Gilford, Hamish Linklater, Henry Thomas, Kristin Lehman, Samantha Sloyan, Igby Rigney, Rahul Kohli, Annarah Cymone, Annabeth Gish, Alex Essoe, Rahul Abburi, Matt Biedel, Michael Trucco, Crystal Balint, Louis Oliver',
  'unknown',
  '2021-09-24 00:00:00',
  2021,
  'TV-MA',
  '1 Season',
  'TV Mysteries',
  'The arrival of a charismatic young priest brings glorious miracles, ominous mysteries and renewed religious fervor to a dying town desperate to believe.',
  2021.0,
  9.0,
  'September',
  0.0,
  None,
  1.0),
 ('s7',
  'Movie',
  'My Little Pony: A New Generation',
  'Robert Cullen, JosÃ© Luis Ucha',
  'Vanessa Hudgens, Kimiko Glenn, James Marsden, Sofia Carson, Liza Koshy, Ken Jeong, Elizabeth Perkins, Jane Krakowski, Michael McKean, Phil LaMarr',
  'unknown',
  '2021-09-24 00:00:00',
  2021,
  'PG',
  '91 min',
  'Children & Family Movies',
  "Equestria's divided. But a bright-eyed hero believes Earth Ponies, Pegasi and Unicorns should be pals â\x80\x94 and, hoof to heart, sheâ\x80\x99s determined to prove it.",
  2021.0,
  9.0,
  'September',
  0.0,
  91.0,
  None),
 ('s8',
  'Movie',
  'Sankofa',
  'Haile Gerima',
  'Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra Duah, Nick Medley, Mutabaruka, Afemo Omilami, Reggie Carter, Mzuri',
  'United States',
  '2021-09-24 00:00:00',
  1993,
  'TV-MA',
  '125 min',
  'Dramas',
  'On a photo shoot in Ghana, an American model slips back in time, becomes enslaved on a plantation and bears witness to the agony of her ancestral past.',
  2021.0,
  9.0,
  'September',
  28.0,
  125.0,
  None),
 ('s8',
  'Movie',
  'Sankofa',
  'Haile Gerima',
  'Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra Duah, Nick Medley, Mutabaruka, Afemo Omilami, Reggie Carter, Mzuri',
  'United States',
  '2021-09-24 00:00:00',
  1993,
  'TV-MA',
  '125 min',
  'Independent Movies',
  'On a photo shoot in Ghana, an American model slips back in time, becomes enslaved on a plantation and bears witness to the agony of her ancestral past.',
  2021.0,
  9.0,
  'September',
  28.0,
  125.0,
  None),
 ('s8',
  'Movie',
  'Sankofa',
  'Haile Gerima',
  'Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra Duah, Nick Medley, Mutabaruka, Afemo Omilami, Reggie Carter, Mzuri',
  'United States',
  '2021-09-24 00:00:00',
  1993,
  'TV-MA',
  '125 min',
  'International Movies',
  'On a photo shoot in Ghana, an American model slips back in time, becomes enslaved on a plantation and bears witness to the agony of her ancestral past.',
  2021.0,
  9.0,
  'September',
  28.0,
  125.0,
  None),
 ('s8',
  'Movie',
  'Sankofa',
  'Haile Gerima',
  'Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra Duah, Nick Medley, Mutabaruka, Afemo Omilami, Reggie Carter, Mzuri',
  'Ghana',
  '2021-09-24 00:00:00',
  1993,
  'TV-MA',
  '125 min',
  'Dramas',
  'On a photo shoot in Ghana, an American model slips back in time, becomes enslaved on a plantation and bears witness to the agony of her ancestral past.',
  2021.0,
  9.0,
  'September',
  28.0,
  125.0,
  None),
 ('s8',
  'Movie',
  'Sankofa',
  'Haile Gerima',
  'Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra Duah, Nick Medley, Mutabaruka, Afemo Omilami, Reggie Carter, Mzuri',
  'Ghana',
  '2021-09-24 00:00:00',
  1993,
  'TV-MA',
  '125 min',
  'Independent Movies',
  'On a photo shoot in Ghana, an American model slips back in time, becomes enslaved on a plantation and bears witness to the agony of her ancestral past.',
  2021.0,
  9.0,
  'September',
  28.0,
  125.0,
  None),
 ('s8',
  'Movie',
  'Sankofa',
  'Haile Gerima',
  'Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra Duah, Nick Medley, Mutabaruka, Afemo Omilami, Reggie Carter, Mzuri',
  'Ghana',
  '2021-09-24 00:00:00',
  1993,
  'TV-MA',
  '125 min',
  'International Movies',
  'On a photo shoot in Ghana, an American model slips back in time, becomes enslaved on a plantation and bears witness to the agony of her ancestral past.',
  2021.0,
  9.0,
  'September',
  28.0,
  125.0,
  None),
 ('s8',
  'Movie',
  'Sankofa',
  'Haile Gerima',
  'Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra Duah, Nick Medley, Mutabaruka, Afemo Omilami, Reggie Carter, Mzuri',
  'Burkina Faso',
  '2021-09-24 00:00:00',
  1993,
  'TV-MA',
  '125 min',
  'Dramas',
  'On a photo shoot in Ghana, an American model slips back in time, becomes enslaved on a plantation and bears witness to the agony of her ancestral past.',
  2021.0,
  9.0,
  'September',
  28.0,
  125.0,
  None),
 ('s8',
  'Movie',
  'Sankofa',
  'Haile Gerima',
  'Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra Duah, Nick Medley, Mutabaruka, Afemo Omilami, Reggie Carter, Mzuri',
  'Burkina Faso',
  '2021-09-24 00:00:00',
  1993,
  'TV-MA',
  '125 min',
  'Independent Movies',
  'On a photo shoot in Ghana, an American model slips back in time, becomes enslaved on a plantation and bears witness to the agony of her ancestral past.',
  2021.0,
  9.0,
  'September',
  28.0,
  125.0,
  None),
 ('s8',
  'Movie',
  'Sankofa',
  'Haile Gerima',
  'Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra Duah, Nick Medley, Mutabaruka, Afemo Omilami, Reggie Carter, Mzuri',
  'Burkina Faso',
  '2021-09-24 00:00:00',
  1993,
  'TV-MA',
  '125 min',
  'International Movies',
  'On a photo shoot in Ghana, an American model slips back in time, becomes enslaved on a plantation and bears witness to the agony of her ancestral past.',
  2021.0,
  9.0,
  'September',
  28.0,
  125.0,
  None),
 ('s8',
  'Movie',
  'Sankofa',
  'Haile Gerima',
  'Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra Duah, Nick Medley, Mutabaruka, Afemo Omilami, Reggie Carter, Mzuri',
  'United Kingdom',
  '2021-09-24 00:00:00',
  1993,
  'TV-MA',
  '125 min',
  'Dramas',
  'On a photo shoot in Ghana, an American model slips back in time, becomes enslaved on a plantation and bears witness to the agony of her ancestral past.',
  2021.0,
  9.0,
  'September',
  28.0,
  125.0,
  None),
 ('s8',
  'Movie',
  'Sankofa',
  'Haile Gerima',
  'Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra Duah, Nick Medley, Mutabaruka, Afemo Omilami, Reggie Carter, Mzuri',
  'United Kingdom',
  '2021-09-24 00:00:00',
  1993,
  'TV-MA',
  '125 min',
  'Independent Movies',
  'On a photo shoot in Ghana, an American model slips back in time, becomes enslaved on a plantation and bears witness to the agony of her ancestral past.',
  2021.0,
  9.0,
  'September',
  28.0,
  125.0,
  None),
 ('s8',
  'Movie',
  'Sankofa',
  'Haile Gerima',
  'Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra Duah, Nick Medley, Mutabaruka, Afemo Omilami, Reggie Carter, Mzuri',
  'United Kingdom',
  '2021-09-24 00:00:00',
  1993,
  'TV-MA',
  '125 min',
  'International Movies',
  'On a photo shoot in Ghana, an American model slips back in time, becomes enslaved on a plantation and bears witness to the agony of her ancestral past.',
  2021.0,
  9.0,
  'September',
  28.0,
  125.0,
  None),
 ('s8',
  'Movie',
  'Sankofa',
  'Haile Gerima',
  'Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra Duah, Nick Medley, Mutabaruka, Afemo Omilami, Reggie Carter, Mzuri',
  'Germany',
  '2021-09-24 00:00:00',
  1993,
  'TV-MA',
  '125 min',
  'Dramas',
  'On a photo shoot in Ghana, an American model slips back in time, becomes enslaved on a plantation and bears witness to the agony of her ancestral past.',
  2021.0,
  9.0,
  'September',
  28.0,
  125.0,
  None),
 ('s8',
  'Movie',
  'Sankofa',
  'Haile Gerima',
  'Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra Duah, Nick Medley, Mutabaruka, Afemo Omilami, Reggie Carter, Mzuri',
  'Germany',
  '2021-09-24 00:00:00',
  1993,
  'TV-MA',
  '125 min',
  'Independent Movies',
  'On a photo shoot in Ghana, an American model slips back in time, becomes enslaved on a plantation and bears witness to the agony of her ancestral past.',
  2021.0,
  9.0,
  'September',
  28.0,
  125.0,
  None),
 ('s8',
  'Movie',
  'Sankofa',
  'Haile Gerima',
  'Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra Duah, Nick Medley, Mutabaruka, Afemo Omilami, Reggie Carter, Mzuri',
  'Germany',
  '2021-09-24 00:00:00',
  1993,
  'TV-MA',
  '125 min',
  'International Movies',
  'On a photo shoot in Ghana, an American model slips back in time, becomes enslaved on a plantation and bears witness to the agony of her ancestral past.',
  2021.0,
  9.0,
  'September',
  28.0,
  125.0,
  None),
 ('s8',
  'Movie',
  'Sankofa',
  'Haile Gerima',
  'Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra Duah, Nick Medley, Mutabaruka, Afemo Omilami, Reggie Carter, Mzuri',
  'Ethiopia',
  '2021-09-24 00:00:00',
  1993,
  'TV-MA',
  '125 min',
  'Dramas',
  'On a photo shoot in Ghana, an American model slips back in time, becomes enslaved on a plantation and bears witness to the agony of her ancestral past.',
  2021.0,
  9.0,
  'September',
  28.0,
  125.0,
  None),
 ('s8',
  'Movie',
  'Sankofa',
  'Haile Gerima',
  'Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra Duah, Nick Medley, Mutabaruka, Afemo Omilami, Reggie Carter, Mzuri',
  'Ethiopia',
  '2021-09-24 00:00:00',
  1993,
  'TV-MA',
  '125 min',
  'Independent Movies',
  'On a photo shoot in Ghana, an American model slips back in time, becomes enslaved on a plantation and bears witness to the agony of her ancestral past.',
  2021.0,
  9.0,
  'September',
  28.0,
  125.0,
  None),
 ('s8',
  'Movie',
  'Sankofa',
  'Haile Gerima',
  'Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra Duah, Nick Medley, Mutabaruka, Afemo Omilami, Reggie Carter, Mzuri',
  'Ethiopia',
  '2021-09-24 00:00:00',
  1993,
  'TV-MA',
  '125 min',
  'International Movies',
  'On a photo shoot in Ghana, an American model slips back in time, becomes enslaved on a plantation and bears witness to the agony of her ancestral past.',
  2021.0,
  9.0,
  'September',
  28.0,
  125.0,
  None),
 ('s9',
  'TV Show',
  'The Great British Baking Show',
  'Andy Devonshire',
  'Mel Giedroyc, Sue Perkins, Mary Berry, Paul Hollywood',
  'United Kingdom',
  '2021-09-24 00:00:00',
  2021,
  'TV-14',
  '9 Seasons',
  'British TV Shows',
  "A talented batch of amateur bakers face off in a 10-week competition, whipping up their best dishes in the hopes of being named the U.K.'s best.",
  2021.0,
  9.0,
  'September',
  0.0,
  None,
  9.0),
 ('s9',
  'TV Show',
  'The Great British Baking Show',
  'Andy Devonshire',
  'Mel Giedroyc, Sue Perkins, Mary Berry, Paul Hollywood',
  'United Kingdom',
  '2021-09-24 00:00:00',
  2021,
  'TV-14',
  '9 Seasons',
  'Reality TV',
  "A talented batch of amateur bakers face off in a 10-week competition, whipping up their best dishes in the hopes of being named the U.K.'s best.",
  2021.0,
  9.0,
  'September',
  0.0,
  None,
  9.0),
 ('s10',
  'Movie',
  'The Starling',
  'Theodore Melfi',
  "Melissa McCarthy, Chris O'Dowd, Kevin Kline, Timothy Olyphant, Daveed Diggs, Skyler Gisondo, Laura Harrier, Rosalind Chao, Kimberly Quinn, Loretta Devine, Ravi Kapoor",
  'United States',
  '2021-09-24 00:00:00',
  2021,
  'PG-13',
  '104 min',
  'Comedies',
  "A woman adjusting to life after a loss contends with a feisty bird that's taken over her garden â\x80\x94 and a husband who's struggling to find a way forward.",
  2021.0,
  9.0,
  'September',
  0.0,
  104.0,
  None),
 ('s10',
  'Movie',
  'The Starling',
  'Theodore Melfi',
  "Melissa McCarthy, Chris O'Dowd, Kevin Kline, Timothy Olyphant, Daveed Diggs, Skyler Gisondo, Laura Harrier, Rosalind Chao, Kimberly Quinn, Loretta Devine, Ravi Kapoor",
  'United States',
  '2021-09-24 00:00:00',
  2021,
  'PG-13',
  '104 min',
  'Dramas',
  "A woman adjusting to life after a loss contends with a feisty bird that's taken over her garden â\x80\x94 and a husband who's struggling to find a way forward.",
  2021.0,
  9.0,
  'September',
  0.0,
  104.0,
  None),
 ('s11',
  'TV Show',
  'Vendetta: Truth, Lies and The Mafia',
  'unknown',
  'unknown',
  'unknown',
  '2021-09-24 00:00:00',
  2021,
  'TV-MA',
  '1 Season',
  'Crime TV Shows',
  'Sicily boasts a bold "Anti-Mafia" coalition. But what happens when those trying to bring down organized crime are accused of being criminals themselves?',
  2021.0,
  9.0,
  'September',
  0.0,
  None,
  1.0),
 ('s11',
  'TV Show',
  'Vendetta: Truth, Lies and The Mafia',
  'unknown',
  'unknown',
  'unknown',
  '2021-09-24 00:00:00',
  2021,
  'TV-MA',
  '1 Season',
  'Docuseries',
  'Sicily boasts a bold "Anti-Mafia" coalition. But what happens when those trying to bring down organized crime are accused of being criminals themselves?',
  2021.0,
  9.0,
  'September',
  0.0,
  None,
  1.0),
 ('s11',
  'TV Show',
  'Vendetta: Truth, Lies and The Mafia',
  'unknown',
  'unknown',
  'unknown',
  '2021-09-24 00:00:00',
  2021,
  'TV-MA',
  '1 Season',
  'International TV Shows',

In [26]:
conn.close()

In [33]:
df.duplicated().sum()

np.int64(0)

In [32]:
df['duration_minutes'].describe()
df['seasons'].describe()

count    6881.000000
mean        1.757739
std         1.594556
min         1.000000
25%         1.000000
50%         1.000000
75%         2.000000
max        17.000000
Name: seasons, dtype: float64

In [34]:
df[df['content_age'] < 0]

     show_id     type                       title               director                                               cast         country date_added  release_year rating   duration                  listed_in                                        description  added_year  added_month added_month_name  content_age  duration_minutes  seasons
1551   s1552  TV Show                       Hilda                unknown  Bella Ramsey, Ameerah Falzon-Ojo, Oliver Nelso...  United Kingdom 2020-12-14          2021  TV-Y7  2 Seasons                   Kids' TV  Fearless, free-spirited Hilda finds new friend...      2020.0         12.0         December         -1.0               NaN      2.0
1551   s1552  TV Show                       Hilda                unknown  Bella Ramsey, Ameerah Falzon-Ojo, Oliver Nelso...          Canada 2020-12-14          2021  TV-Y7  2 Seasons                   Kids' TV  Fearless, free-spirited Hilda finds new friend...      2020.0         12.0         December         -1.0               NaN      2.0
1551   s1552  TV Show                       Hilda                unknown  Bella Ramsey, Ameerah Falzon-Ojo, Oliver Nelso...   United States 2020-12-14          2021  TV-Y7  2 Seasons                   Kids' TV  Fearless, free-spirited Hilda finds new friend...      2020.0         12.0         December         -1.0               NaN      2.0
1696   s1697  TV Show                Polly Pocket                unknown  Emily Tennant, Shannon Chan-Kent, Kazumi Evans...          Canada 2020-11-15          2021   TV-Y  2 Seasons                   Kids' TV  After uncovering a magical locket that allows ...      2020.0         11.0         November         -1.0               NaN      2.0
1696   s1697  TV Show                Polly Pocket                unknown  Emily Tennant, Shannon Chan-Kent, Kazumi Evans...   United States 2020-11-15          2021   TV-Y  2 Seasons                   Kids' TV  After uncovering a magical locket that allows ...      2020.0         11.0         November         -1.0               NaN      2.0
1696   s1697  TV Show                Polly Pocket                unknown  Emily Tennant, Shannon Chan-Kent, Kazumi Evans...         Ireland 2020-11-15          2021   TV-Y  2 Seasons                   Kids' TV  After uncovering a magical locket that allows ...      2020.0         11.0         November         -1.0               NaN      2.0
2920   s2921  TV Show               Love Is Blind                unknown                        Nick Lachey, Vanessa Lachey   United States 2020-02-13          2021  TV-MA   1 Season                 Reality TV  Nick and Vanessa Lachey host this social exper...      2020.0          2.0         February         -1.0               NaN      1.0
2920   s2921  TV Show               Love Is Blind                unknown                        Nick Lachey, Vanessa Lachey   United States 2020-02-13          2021  TV-MA   1 Season          Romantic TV Shows  Nick and Vanessa Lachey host this social exper...      2020.0          2.0         February         -1.0               NaN      1.0
3168   s3169  TV Show                Fuller House                unknown  Candace Cameron Bure, Jodie Sweetin, Andrea Ba...   United States 2019-12-06          2020  TV-PG  5 Seasons                TV Comedies  The Tanner familyâs adventures continue as D...      2019.0         12.0         December         -1.0               NaN      5.0
3287   s3288  TV Show          Maradona in Mexico                unknown                             Diego Armando Maradona       Argentina 2019-11-13          2020  TV-MA   1 Season                 Docuseries  In this docuseries, soccer great Diego Maradon...      2019.0         11.0         November         -1.0               NaN      1.0
3287   s3288  TV Show          Maradona in Mexico                unknown                             Diego Armando Maradona       Argentina 2019-11-13          2020  TV-MA   1 Season  Spanish-Language TV Shows  In this docuseries, soccer great Diego Maradon...      2019.0         11.0         November         -1.0               NaN      1.0
3287   s3288  TV Show          Maradona in Mexico                unknown                             Diego Armando Maradona   United States 2019-11-13          2020  TV-MA   1 Season                 Docuseries  In this docuseries, soccer great Diego Maradon...      2019.0         11.0         November         -1.0               NaN      1.0
3287   s3288  TV Show          Maradona in Mexico                unknown                             Diego Armando Maradona   United States 2019-11-13          2020  TV-MA   1 Season  Spanish-Language TV Shows  In this docuseries, soccer great Diego Maradon...      2019.0         11.0         November         -1.0               NaN      1.0
3287   s3288  TV Show          Maradona in Mexico                unknown                             Diego Armando Maradona          Mexico 2019-11-13          2020  TV-MA   1 Season                 Docuseries  In this docuseries, soccer great Diego Maradon...      2019.0         11.0         November         -1.0               NaN      1.0
3287   s3288  TV Show          Maradona in Mexico                unknown                             Diego Armando Maradona          Mexico 2019-11-13          2020  TV-MA   1 Season  Spanish-Language TV Shows  In this docuseries, soccer great Diego Maradon...      2019.0         11.0         November         -1.0               NaN      1.0
3369   s3370  TV Show             BoJack Horseman                unknown  Will Arnett, Aaron Paul, Amy Sedaris, Alison B...   United States 2019-10-25          2020  TV-MA  6 Seasons                TV Comedies  Meet the most beloved sitcom horse of the '90s...      2019.0         10.0          October         -1.0               NaN      6.0
3433   s3434  TV Show            The Hook Up Plan                unknown  Marc Ruchmann, Zita Hanrot, Sabrina Ouazani, J...          France 2019-10-11          2020  TV-MA  2 Seasons     International TV Shows  When Parisian Elsa gets hung up on her ex, her...      2019.0         10.0          October         -1.0               NaN      2.0
3433   s3434  TV Show            The Hook Up Plan                unknown  Marc Ruchmann, Zita Hanrot, Sabrina Ouazani, J...          France 2019-10-11          2020  TV-MA  2 Seasons          Romantic TV Shows  When Parisian Elsa gets hung up on her ex, her...      2019.0         10.0          October         -1.0               NaN      2.0
3433   s3434  TV Show            The Hook Up Plan                unknown  Marc Ruchmann, Zita Hanrot, Sabrina Ouazani, J...          France 2019-10-11          2020  TV-MA  2 Seasons                TV Comedies  When Parisian Elsa gets hung up on her ex, her...      2019.0         10.0          October         -1.0               NaN      2.0
4844   s4845  TV Show   Unbreakable Kimmy Schmidt                unknown  Ellie Kemper, Jane Krakowski, Tituss Burgess, ...   United States 2018-05-30          2019  TV-14  4 Seasons                TV Comedies  When a woman is rescued from a doomsday cult a...      2018.0          5.0              May         -1.0               NaN      4.0
4845   s4846  TV Show        Arrested Development                unknown  Jason Bateman, Portia de Rossi, Will Arnett, M...   United States 2018-05-29          2019  TV-MA  5 Seasons                TV Comedies  It's the Emmy-winning story of a wealthy famil...      2018.0          5.0              May         -1.0               NaN      5.0
5394   s5395    Movie  Hans Teeuwen: Real Rancour  Doesjka van Hoogdalem                                       Hans Teeuwen     Netherlands 2017-07-01          2018  TV-MA     86 min            Stand-Up Comedy  Comedian Hans Teeuwen rebels against political...      2017.0          7.0             July         -1.0              86.0      NaN
5658   s5659  TV Show                      Sense8                unknown  Tuppence Middleton, Brian J. Smith, Doona Bae,...   United States 2016-12-23          2018  TV-MA  2 Seasons             Crime TV Shows  From the creators of "The Matrix" and "Babylon...      2016.0         12.0         December         -2.0               NaN      2.0
5658   s5659  TV Show                      Sense8                unknown  Tuppence Middleton, Brian J. Smith, Doona Bae,...   United States 2016-12-23          2018  TV-MA  2 Seasons                  TV Dramas  From the creators of "The Matrix" and "Babylon...      2016.0         12.0         December         -2.0               NaN      2.0
5658   s5659  TV Show                      Sense8                unknown  Tuppence Middleton, Brian J. Smith, Doona Bae,...   United States 2016-12-23          2018  TV-MA  2 Seasons               TV Mysteries  From the creators of "The Matrix" and "Babylon...      2016.0         12.0         December         -2.0               NaN      2.0
5677   s5678  TV Show                 Tokyo Trial                unknown  Marcel Hensema, Paul Freeman, Irrfan Khan, Sta...          Canada 2016-12-13          2017  TV-MA   1 Season     International TV Shows  In the wake of World War II, 11 Allied judges ...      2016.0         12.0         December         -1.0               NaN      1.0
5677   s5678  TV Show                 Tokyo Trial                unknown  Marcel Hensema, Paul Freeman, Irrfan Khan, Sta...          Canada 2016-12-13          2017  TV-MA   1 Season                  TV Dramas  In the wake of World War II, 11 Allied judges ...      2016.0         12.0         December         -1.0               NaN      1.0
5677   s5678  TV Show                 Tokyo Trial                unknown  Marcel Hensema, Paul Freeman, Irrfan Khan, Sta...           Japan 2016-12-13          2017  TV-MA   1 Season     International TV Shows  In the wake of World War II, 11 Allied judges ...      2016.0         12.0         December         -1.0               NaN      1.0
5677   s5678  TV Show                 Tokyo Trial                unknown  Marcel Hensema, Paul Freeman, Irrfan Khan, Sta...           Japan 2016-12-13          2017  TV-MA   1 Season                  TV Dramas  In the wake of World War II, 11 Allied judges ...      2016.0         12.0         December         -1.0               NaN      1.0
5677   s5678  TV Show                 Tokyo Trial                unknown  Marcel Hensema, Paul Freeman, Irrfan Khan, Sta...     Netherlands 2016-12-13          2017  TV-MA   1 Season     International TV Shows  In the wake of World War II, 11 Allied judges ...      2016.0         12.0         December         -1.0               NaN      1.0
5677   s5678  TV Show                 Tokyo Trial                unknown  Marcel Hensema, Paul Freeman, Irrfan Khan, Sta...     Netherlands 2016-12-13          2017  TV-MA   1 Season                  TV Dramas  In the wake of World War II, 11 Allied judges ...      2016.0         12.0         December         -1.0               NaN      1.0
7063   s7064    Movie                    Incoming          Eric Zaragosa  Scott Adkins, Aaron McCusker, Vahldin Prelic, ...          Serbia 2018-10-26          2019  TV-MA     89 min         Action & Adventure  When an imprisoned terrorist cell hijacks a hi...      2018.0         10.0          October         -1.0              89.0      NaN
7063   s7064    Movie                    Incoming          Eric Zaragosa  Scott Adkins, Aaron McCusker, Vahldin Prelic, ...          Serbia 2018-10-26          2019  TV-MA     89 min           Sci-Fi & Fantasy  When an imprisoned terrorist cell hijacks a hi...      2018.0         10.0          October         -1.0              89.0      NaN
7063   s7064    Movie                    Incoming          Eric Zaragosa  Scott Adkins, Aaron McCusker, Vahldin Prelic, ...   United States 2018-10-26          2019  TV-MA     89 min         Action & Adventure  When an imprisoned terrorist cell hijacks a hi...      2018.0         10.0          October         -1.0              89.0      NaN
7063   s7064    Movie                    Incoming          Eric Zaragosa  Scott Adkins, Aaron McCusker, Vahldin Prelic, ...   United States 2018-10-26          2019  TV-MA     89 min           Sci-Fi & Fantasy  When an imprisoned terrorist cell hijacks a hi...      2018.0         10.0          October         -1.0              89.0      NaN
7112   s7113  TV Show                 Jack Taylor            Stuart Orme  Iain Glen, Killian Scott, Nora-Jane Noone, Tar...   United States 2013-03-31          2016  TV-MA   1 Season             Crime TV Shows  Ken Bruen's bestselling crime novels leap to l...      2013.0          3.0            March         -3.0               NaN      1.0
7112   s7113  TV Show                 Jack Taylor            Stuart Orme  Iain Glen, Killian Scott, Nora-Jane Noone, Tar...   United States 2013-03-31          2016  TV-MA   1 Season     International TV Shows  Ken Bruen's bestselling crime novels leap to l...      2013.0          3.0            March         -3.0               NaN      1.0
7112   s7113  TV Show                 Jack Taylor            Stuart Orme  Iain Glen, Killian Scott, Nora-Jane Noone, Tar...   United States 2013-03-31          2016  TV-MA   1 Season                  TV Dramas  Ken Bruen's bestselling crime novels leap to l...      2013.0          3.0            March         -3.0               NaN      1.0
7112   s7113  TV Show                 Jack Taylor            Stuart Orme  Iain Glen, Killian Scott, Nora-Jane Noone, Tar...         Ireland 2013-03-31          2016  TV-MA   1 Season             Crime TV Shows  Ken Bruen's bestselling crime novels leap to l...      2013.0          3.0            March         -3.0               NaN      1.0
7112   s7113  TV Show                 Jack Taylor            Stuart Orme  Iain Glen, Killian Scott, Nora-Jane Noone, Tar...         Ireland 2013-03-31          2016  TV-MA   1 Season     International TV Shows  Ken Bruen's bestselling crime novels leap to l...      2013.0          3.0            March         -3.0               NaN      1.0
7112   s7113  TV Show                 Jack Taylor            Stuart Orme  Iain Glen, Killian Scott, Nora-Jane Noone, Tar...         Ireland 2013-03-31          2016  TV-MA   1 Season                  TV Dramas  Ken Bruen's bestselling crime novels leap to l...      2013.0          3.0            March         -3.0               NaN      1.0

In [37]:
df.to_csv("netflix_cleaned2.csv", index=False)

In [35]:
df['duration_minutes'].describe()
df['seasons'].describe()

count    6881.000000
mean        1.757739
std         1.594556
min         1.000000
25%         1.000000
50%         1.000000
75%         2.000000
max        17.000000
Name: seasons, dtype: float64